### ISSUE TITLE
vgg-cifar.caffemodel missing 

### ISSUE THREAD

**Issue by ZhuweiQin** [slothkong/DNN-Pruning#1]
Hello! Thank you very much for your good implementation! Could you please tell me how can I download the weight file?

**Comment by slothkong** [comment]
In the the `temp` folter there is a `vgg-cifar.prototxt` file you can use to train obtain the same `.caffemodel` I used for the demo. Download the cifar dataset and train it using caffe (it shouldn't take more than an hour to train). Just in case I will upload the file later this week.
P.S: Sorry for the late replay

**Comment by ZhuweiQin** [comment]
Thanks for your reply. Just as you said, I train the VGG16 on cifar10 by using this solver file:https://github.com/yihui-he/resnet-cifar10-caffe/blob/master/vgg16/solver.prototxt. But the final accuracy is only 90.2%, the model baseline accuracy in most papers is greater than 92.2%. Do you know how to achieve that state of art result? Thanks~
And I found another problem in this code, after I saved the pruned model in the local disk, the model accuracy is only around 20%, but this saved model accuracy could be 80% before saving. Could please try that, just pruning some filters, save the model and test the accuracy. Thanks~
